"""Initial migration - all tables

Revision ID: dd29352220f8
Revises: 
Create Date: 2025-12-24 20:18:13.138136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd29352220f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('hire_decision', sa.Boolean(), nullable=True))
    op.add_column('applications', sa.Column('ai_score_at_decision', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'ai_score_at_decision')
    op.drop_column('applications', 'hire_decision')
    # ### end Alembic commands ###
